Name: Nishan Thapa

Student ID: 2408890

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Verify Python Version


In [ ]:
import sys

if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


---
# 1. Python Fundamentals

## 1.1: Data Types in Python

In [ ]:
# Numeric Types
age         = 23        # int
pi          = 3.14      # float
temperature = -5.5      # float
z           = 3 + 4j    # complex

print("Numeric Types")
print(f"age         = {age}   -> type: {type(age)}")
print(f"pi          = {pi}  -> type: {type(pi)}")
print(f"temperature = {temperature}  -> type: {type(temperature)}")
print(f"z           = {z}  -> type: {type(z)}")

Numeric Types
age         = 23   -> type: <class 'int'>
pi          = 3.14  -> type: <class 'float'>
temperature = -5.5  -> type: <class 'float'>
z           = (3+4j)  -> type: <class 'complex'>


In [ ]:
# String (immutable sequence)
name     = "Alice"
greeting = 'Hello'

print("String Slicing")
print(f"First letter  : {name[0]}")       # positive index
print(f"Last letter   : {name[-1]}")      # negative index
print(f"2nd to 4th    : {name[1:4]}")     # slice
print(f"First two     : {name[:2]}")      # slice from start
print(f"From 3rd char : {name[2:]}")      # slice to end

String Slicing
First letter  : A
Last letter   : e
2nd to 4th    : lic
First two     : Al
From 3rd char : ice


In [ ]:
# List (mutable sequence)
fruits = ["apple", "banana", "cherry"]
fruits.append("mango")          # add to end
print("List after append:", fruits)

fruits[0] = "avocado"           # mutate an element
print("List after mutation:", fruits)

List after append: ['apple', 'banana', 'cherry', 'mango']
List after mutation: ['avocado', 'banana', 'cherry', 'mango']


In [ ]:
# Tuple (immutable sequence)
colors = ('red', 'green', 'yellow', 'blue')
print("First element     :", colors[0])
print("Last two elements :", colors[2:])

# Uncommenting the next line will raise AttributeError — tuples cannot be changed
# colors[0] = 'purple'

First element     : red
Last two elements : ('yellow', 'blue')


In [ ]:
# Dictionary
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello, my name is {person['name']}. I am {person['age']} years old.")
print("Keys   :", list(person.keys()))
print("Values :", list(person.values()))

Hello, my name is John. I am 30 years old.
Keys   : ['name', 'age', 'city']
Values : ['John', 30, 'Pittsburgh']


In [ ]:
# Set (unique elements)
unique_numbers = {1, 2, 3, 3, 3, 4, 5}   # duplicates are removed automatically
print("Set:", unique_numbers)

# ── Boolean ───────────────────────────────────────────────
is_student  = True
has_license = False
print(f"is_student  → {type(is_student)}")
print(f"has_license → {type(has_license)}")

Set: {1, 2, 3, 4, 5}
is_student  → <class 'bool'>
has_license → <class 'bool'>


## 1.2: Logical Statements & Comparison Operators

In [ ]:
#  if / elif / else
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

# Logical operators: and, or, not
x, y = 5, 10
print(x > 0 and y < 20)   # True
print(x > 0 or  y > 20)   # True
print(not x == 0)          # True

Positive
True
True
True


## 1.3: Loops

In [ ]:
# for loop
print(" for loop ")
for fruit in ["apple", "banana", "cherry"]:
    print(fruit)

# while loop
print("while loop ")
count = 0
while count < 5:
    print("Count:", count)
    count += 1

# break
print(" break — stops at apple ")
for fruit in ["apple", "banana", "orange"]:
    print(fruit)
    if fruit == "apple":
        break

# continue
print(" continue — skips apple ")
for fruit in ["apple", "banana", "orange"]:
    if fruit == "apple":
        continue
    print(fruit)

 for loop 
apple
banana
cherry
while loop 
Count: 0
Count: 1
Count: 2
Count: 3
Count: 4
 break — stops at apple 
apple
 continue — skips apple 
banana
orange


## 1.4: Functions, Docstrings, Global vs Local Variables

In [ ]:
def add_binary(a, b):
    """
    Returns the sum of two decimal integers as a binary string.

    Parameters:
        a (int): First integer.
        b (int): Second integer.

    Returns:
        str: Binary representation of a + b.
    """
    binary_sum = bin(a + b)[2:]   # bin() returns '0b...' — [2:] removes prefix
    return binary_sum

print(add_binary(5, 3))   # 1000  (5+3=8 in binary)
help(add_binary)           # prints the docstring

1000
Help on function add_binary in module __main__:

add_binary(a, b)
    Returns the sum of two decimal integers as a binary string.

    Parameters:
        a (int): First integer.
        b (int): Second integer.

    Returns:
        str: Binary representation of a + b.



In [ ]:
#  Global vs Local scope
x = 10   # global

def show_global():
    print("Inside function, x =", x)   # reads global

def modify_global():
    global x
    x = 99   # modifies global

show_global()      # 10
modify_global()
print("After modify_global(), x =", x)   # 99

Inside function, x = 10
After modify_global(), x = 99


## 1.5: Exception & Error Handling

In [ ]:
# try / except / finally
try:
    num = int(input("Enter a number (try 0 or a letter): "))
    print("Result:", 10 / num)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid input — please enter a number.")
finally:
    print("try-except block finished.")

Enter a number (try 0 or a letter): 31
Result: 0.3225806451612903
try-except block finished.


In [ ]:
# Custom / raise exception
def check_age(age):
    """Raises ValueError if age is negative."""
    if age < 0:
        raise ValueError("Age cannot be negative.")
    print("Valid age:", age)

try:
    check_age(-1)
except ValueError as e:
    print("Caught:", e)

Caught: Age cannot be negative.


# PART 2: Python Exercises


## Task 1: Unit Converter

Create a program that converts between:
- **Length**: metres to feet and vice versa
- **Weight**: kilograms to pounds and vice versa
- **Volume**: litres to gallons and vice versa

In [ ]:
# Conversion factors
CONVERSION_FACTORS = {
    "length": {
        "m_to_ft" : 3.28084,
        "ft_to_m" : 0.3048
    },
    "weight": {
        "kg_to_lbs": 2.20462,
        "lbs_to_kg": 0.453592
    },
    "volume": {
        "l_to_gal" : 0.264172,
        "gal_to_l" : 3.78541
    }
}


def convert_length(value, direction):
    """
    Convert a length value between metres and feet.

    Parameters:
        value (float)    : The numeric value to convert.
        direction (str)  : 'm_to_ft' or 'ft_to_m'.

    Returns:
        float: The converted value.

    Raises:
        ValueError: If direction is not recognised.
    """
    factor = CONVERSION_FACTORS["length"].get(direction)
    if factor is None:
        raise ValueError(f"Unknown direction '{direction}'. Use 'm_to_ft' or 'ft_to_m'.")
    return value * factor


def convert_weight(value, direction):
    """
    Convert a weight value between kilograms and pounds.

    Parameters:
        value (float)    : The numeric value to convert.
        direction (str)  : 'kg_to_lbs' or 'lbs_to_kg'.

    Returns:
        float: The converted value.
    """
    factor = CONVERSION_FACTORS["weight"].get(direction)
    if factor is None:
        raise ValueError(f"Unknown direction '{direction}'. Use 'kg_to_lbs' or 'lbs_to_kg'.")
    return value * factor


def convert_volume(value, direction):
    """
    Convert a volume value between litres and gallons.

    Parameters:
        value (float)    : The numeric value to convert.
        direction (str)  : 'l_to_gal' or 'gal_to_l'.

    Returns:
        float: The converted value.
    """
    factor = CONVERSION_FACTORS["volume"].get(direction)
    if factor is None:
        raise ValueError(f"Unknown direction '{direction}'. Use 'l_to_gal' or 'gal_to_l'.")
    return value * factor


def unit_converter():
    """
    Interactive unit converter.
    Prompts user to select a conversion category and value.
    Handles invalid inputs using try-except.
    """
    print("\n=== Unit Converter ===")
    print("1. Length  (metres <-> feet)")
    print("2. Weight  (kg <-> pounds)")
    print("3. Volume  (litres <-> gallons)")

    category = input("\nChoose category (1 / 2 / 3): ").strip()

    try:
        value = float(input("Enter the value to convert: "))
    except ValueError:
        print("Invalid value — please enter a number.")
        return

    try:
        if category == "1":
            direction = input("Direction — type 'm_to_ft' or 'ft_to_m': ").strip()
            result    = convert_length(value, direction)
            unit_in, unit_out = ("m", "ft") if direction == "m_to_ft" else ("ft", "m")

        elif category == "2":
            direction = input("Direction — type 'kg_to_lbs' or 'lbs_to_kg': ").strip()
            result    = convert_weight(value, direction)
            unit_in, unit_out = ("kg", "lbs") if direction == "kg_to_lbs" else ("lbs", "kg")

        elif category == "3":
            direction = input("Direction — type 'l_to_gal' or 'gal_to_l': ").strip()
            result    = convert_volume(value, direction)
            unit_in, unit_out = ("L", "gal") if direction == "l_to_gal" else ("gal", "L")

        else:
            print("Invalid category. Choose 1, 2, or 3.")
            return

        print(f"\n {value} {unit_in} = {result:.4f} {unit_out}")

    except ValueError as e:
        print(f"Error: {e}")


# Run the converter
unit_converter()


=== Unit Converter ===
1. Length  (metres <-> feet)
2. Weight  (kg <-> pounds)
3. Volume  (litres <-> gallons)

Choose category (1 / 2 / 3): 2
Enter the value to convert: 10
Direction — type 'kg_to_lbs' or 'lbs_to_kg': kg_to_lbs

 10.0 kg = 22.0462 lbs


## Task : Mathematical Operations on a List of Numbers

In [ ]:
def compute_sum(numbers):
    """
    Return the sum of a list of numbers.

    Parameters:
        numbers (list): Non-empty list of floats/ints.

    Returns:
        float: Sum of all elements.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Return the average of a list of numbers.

    Parameters:
        numbers (list): Non-empty list of floats/ints.

    Returns:
        float: Mean value.
    """
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Return the maximum value in a list.

    Parameters:
        numbers (list): Non-empty list of floats/ints.

    Returns:
        float: The largest element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    result = numbers[0]
    for n in numbers:
        if n > result:
            result = n
    return result


def compute_minimum(numbers):
    """
    Return the minimum value in a list.

    Parameters:
        numbers (list): Non-empty list of floats/ints.

    Returns:
        float: The smallest element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    result = numbers[0]
    for n in numbers:
        if n < result:
            result = n
    return result


def math_operations_menu():
    """
    Interactive menu to perform mathematical operations on a user-supplied list.
    """
    print("\n=== Mathematical Operations ===")
    print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

    operation = input("\nChoose operation (1 / 2 / 3 / 4): ").strip()

    raw = input("Enter numbers separated by spaces: ").strip()

    try:
        numbers = [float(x) for x in raw.split()]
    except ValueError:
        print("Invalid input — please enter numbers only.")
        return

    try:
        ops = {"1": compute_sum, "2": compute_average,
               "3": compute_maximum, "4": compute_minimum}
        labels = {"1": "Sum", "2": "Average", "3": "Maximum", "4": "Minimum"}

        if operation not in ops:
            print("Invalid choice.")
            return

        result = ops[operation](numbers)
        print(f"\n{labels[operation]}: {result}")

    except ValueError as e:
        print(f"Error: {e}")


math_operations_menu()


=== Mathematical Operations ===
1. Sum
2. Average
3. Maximum
4. Minimum

Choose operation (1 / 2 / 3 / 4): 1
Enter numbers separated by spaces: 25 33

Sum: 58.0


---
## Tasks 3-9: List Manipulation

In [ ]:
# Task 3 — Extract every other element (starting from index 0)
def extract_every_other(lst):
    """
    Return every other element starting from the first.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Elements at even indices.

    Example:
        [1,2,3,4,5,6] → [1,3,5]
    """
    return lst[::2]

print("extract_every_other:", extract_every_other([1, 2, 3, 4, 5, 6]))

extract_every_other: [1, 3, 5]


In [ ]:
# Task 4 — Slice a sublist (start to end, inclusive)
def get_sublist(lst, start, end):
    """
    Return elements from index start to end (inclusive).

    Parameters:
        lst   (list): Input list.
        start (int) : Start index.
        end   (int) : End index (inclusive).

    Returns:
        list: Sub-list from start to end.

    Example:
        ([1,2,3,4,5,6], 2, 4) → [3,4,5]
    """
    return lst[start:end + 1]   # +1 because Python slicing is exclusive at the end

print("get_sublist:", get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

get_sublist: [3, 4, 5]


In [ ]:
# Task 5 — Reverse a list using slicing
def reverse_list(lst):
    """
    Return the list in reverse order using slicing.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Reversed list.

    Example:
        [1,2,3,4,5] → [5,4,3,2,1]
    """
    return lst[::-1]   # step of -1 reverses the list

print("reverse_list:", reverse_list([1, 2, 3, 4, 5]))

reverse_list: [5, 4, 3, 2, 1]


In [ ]:
# Task 6 — Remove first and last elements
def remove_first_last(lst):
    """
    Return the list without its first and last elements.

    Parameters:
        lst (list): Input list (must have at least 2 elements).

    Returns:
        list: List with first and last elements removed.

    Example:
        [1,2,3,4,5] → [2,3,4]
    """
    return lst[1:-1]

print("remove_first_last:", remove_first_last([1, 2, 3, 4, 5]))

remove_first_last: [2, 3, 4]


In [ ]:
# Task 7 — Get the first n elements
def get_first_n(lst, n):
    """
    Return the first n elements of the list.

    Parameters:
        lst (list): Input list.
        n   (int) : Number of elements to return.

    Returns:
        list: First n elements.

    Example:
        ([1,2,3,4,5], 3) → [1,2,3]
    """
    return lst[:n]

print("get_first_n:", get_first_n([1, 2, 3, 4, 5], 3))

get_first_n: [1, 2, 3]


In [ ]:
# Task 8 — Get the last n elements
def get_last_n(lst, n):
    """
    Return the last n elements of the list.

    Parameters:
        lst (list): Input list.
        n   (int) : Number of elements to return from the end.

    Returns:
        list: Last n elements.

    Example:
        ([1,2,3,4,5], 2) → [4,5]
    """
    return lst[-n:]

print("get_last_n:", get_last_n([1, 2, 3, 4, 5], 2))

In [ ]:
# Task 9 — Extract elements in reverse order, skipping one, starting from second-to-last
def reverse_skip(lst):
    """
    Return every second element starting from the second-to-last, moving backward.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Elements at positions -2, -4, -6, ...

    Example:
        [1,2,3,4,5,6] → [5,3,1]
    """
    return lst[-2::-2]   # start at second-to-last, step -2 (skip one going backwards)

print("reverse_skip:", reverse_skip([1, 2, 3, 4, 5, 6]))

reverse_skip: [5, 3, 1]


---
## Tasks 10-17: Nested List Operations

In [ ]:
# Task 10 — Flatten a nested list (one level deep)
def flatten(lst):
    """
    Flatten a singly-nested list into a 1D list.

    Parameters:
        lst (list): Nested list (one level of nesting).

    Returns:
        list: Flat list of all elements.

    Example:
        [[1,2],[3,4],[5]] → [1,2,3,4,5]
    """
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

print("flatten:", flatten([[1, 2], [3, 4], [5]]))

flatten: [1, 2, 3, 4, 5]


In [ ]:
# Task 11 — Access element by indices list
def access_nested_element(lst, indices):
    """
    Access an element in a nested list given a sequence of indices.

    Parameters:
        lst     (list): Nested list.
        indices (list): List of integer indices to follow.

    Returns:
        The element at the given position.

    Example:
        ([[1,2,3],[4,5,6],[7,8,9]], [1,2]) → 6
    """
    element = lst
    for idx in indices:
        element = element[idx]   # drill into the nested structure step by step
    return element

nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("access_nested_element:", access_nested_element(nested, [1, 2]))

access_nested_element: 6


In [ ]:
# Task 12 — Sum all elements in a nested list (any depth)
def sum_nested(lst):
    """
    Recursively compute the sum of all numeric elements in a nested list.

    Parameters:
        lst (list): Nested list of numbers.

    Returns:
        float/int: Sum of all elements.

    Example:
        [[1,2],[3,[4,5]],6] → 21
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recurse into sub-list
        else:
            total += item
    return total

print("sum_nested:", sum_nested([[1, 2], [3, [4, 5]], 6]))

sum_nested: 21


In [ ]:
# Task 13 — Remove all occurrences of an element from a nested list
def remove_element(lst, elem):
    """
    Remove all occurrences of elem from a singly-nested list.

    Parameters:
        lst  (list): Nested list.
        elem       : Element to remove.

    Returns:
        list: Nested list with elem removed.

    Example:
        ([[1,2],[3,2],[4,5]], 2) → [[1],[3],[4,5]]
    """
    return [[item for item in sublist if item != elem] for sublist in lst]

print("remove_element:", remove_element([[1, 2], [3, 2], [4, 5]], 2))

remove_element: [[1], [3], [4, 5]]


In [ ]:
# Task 14 — Find maximum element in a nested list
def find_max(lst):
    """
    Recursively find the maximum element in a nested list.

    Parameters:
        lst (list): Nested list of numbers.

    Returns:
        The maximum numeric value.

    Example:
        [[1,2],[3,[4,5]],6] → 6
    """
    max_val = None
    for item in lst:
        candidate = find_max(item) if isinstance(item, list) else item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val

print("find_max:", find_max([[1, 2], [3, [4, 5]], 6]))

find_max: 6


In [ ]:
# Task 15 — Count occurrences of an element in a nested list
def count_occurrences(lst, elem):
    """
    Count how many times elem appears in a nested list.

    Parameters:
        lst  (list): Nested list.
        elem       : Element to count.

    Returns:
        int: Count of elem.

    Example:
        ([[1,2],[2,3],[2,4]], 2) → 3
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print("count_occurrences:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

count_occurrences: 3


In [ ]:
# Task 16 — Deep flatten (any depth)
def deep_flatten(lst):
    """
    Recursively flatten a deeply nested list to a single 1D list.

    Parameters:
        lst (list): Arbitrarily nested list.

    Returns:
        list: Flat list containing all leaf values.

    Example:
        [[[1,2],[3,4]],[[5,6],[7,8]]] → [1,2,3,4,5,6,7,8]
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))   # extend avoids nested lists
        else:
            result.append(item)
    return result

print("deep_flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

deep_flatten: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Task 17 — Average of all elements in a nested list
def average_nested(lst):
    """
    Compute the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list of numbers.

    Returns:
        float: Mean of all elements.

    Example:
        [[1,2],[3,4],[5,6]] → 3.5
    """
    flat   = deep_flatten(lst)   # reuse the function above
    return sum(flat) / len(flat)

print("average_nested:", average_nested([[1, 2], [3, 4], [5, 6]]))

average_nested: 3.5


# PART 3: NumPy

In [ ]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


In [ ]:
# Creating different dimensional arrays
zero_dim = np.array(5)                      # scalar — 0D
one_dim  = np.array([1, 2, 3])             # vector — 1D
two_dim  = np.array([[1, 2], [3, 4]])      # matrix — 2D
three_dim = np.array([[[1,2],[3,4]],
                      [[5,6],[7,8]]])       # tensor — 3D

for name, arr in [("0D", zero_dim), ("1D", one_dim),
                  ("2D", two_dim), ("3D", three_dim)]:
    print(f"\n{name} Array:\n{arr}")
    print(f"  ndim  = {arr.ndim}")
    print(f"  shape = {arr.shape}")
    print(f"  size  = {arr.size}")
    print(f"  dtype = {arr.dtype}")


0D Array:
5
  ndim  = 0
  shape = ()
  size  = 1
  dtype = int64

1D Array:
[1 2 3]
  ndim  = 1
  shape = (3,)
  size  = 3
  dtype = int64

2D Array:
[[1 2]
 [3 4]]
  ndim  = 2
  shape = (2, 2)
  size  = 4
  dtype = int64

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
  ndim  = 3
  shape = (2, 2, 2)
  size  = 8
  dtype = int64


In [ ]:
# Key array attributes
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr_2d)
print("Shape     :", arr_2d.shape)      # (2,3)
print("Size      :", arr_2d.size)       # 6
print("Item size :", arr_2d.itemsize)   # bytes per element
print("Total bytes:", arr_2d.nbytes)
print("Transpose :\n", arr_2d.T)
print("As float  :\n", arr_2d.astype(float))

Array:
 [[1 2 3]
 [4 5 6]]
Shape     : (2, 3)
Size      : 6
Item size : 8
Total bytes: 48
Transpose :
 [[1 4]
 [2 5]
 [3 6]]
As float  :
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
#  Creating arrays
print("arange(1,10)      :", np.arange(1, 10))
print("arange(0,1,0.2)   :", np.arange(0, 1, 0.2))
print("linspace(0,1,5)   :", np.linspace(0, 1, 5))
print("ones (2,3)        :\n", np.ones((2, 3)))
print("zeros(2,3)        :\n", np.zeros((2, 3)))
print("eye(3)            :\n", np.eye(3))
print("full(2,3, 7)      :\n", np.full((2, 3), 7))

arange(1,10)      : [1 2 3 4 5 6 7 8 9]
arange(0,1,0.2)   : [0.  0.2 0.4 0.6 0.8]
linspace(0,1,5)   : [0.   0.25 0.5  0.75 1.  ]
ones (2,3)        :
 [[1. 1. 1.]
 [1. 1. 1.]]
zeros(2,3)        :
 [[0. 0. 0.]
 [0. 0. 0.]]
eye(3)            :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full(2,3, 7)      :
 [[7 7 7]
 [7 7 7]]


In [ ]:
# Reshape
arr = np.arange(1, 7)             # [1,2,3,4,5,6]
reshaped = arr.reshape(2, 3)      # reshape to 2 rows, 3 cols
print("Original :", arr)
print("Reshaped :\n", reshaped)

Original : [1 2 3 4 5 6]
Reshaped :
 [[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking and concatenation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("hstack (side by side):\n", np.hstack((a, b)))
print("vstack (top to bottom):\n", np.vstack((a, b)))
print("concatenate axis=0:\n", np.concatenate((a, b), axis=0))
print("concatenate axis=1:\n", np.concatenate((a, b), axis=1))

hstack (side by side):
 [[1 2 5 6]
 [3 4 7 8]]
vstack (top to bottom):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Indexing and Slicing
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Element [0,1]     :", arr2d[0, 1])       # 2
print("Last element      :", arr2d[-1, -1])      # 9
print("First 2 rows, last 2 cols:\n", arr2d[0:2, 1:3])  # [[2,3],[5,6]]
print("Boolean mask > 5  :", arr2d[arr2d > 5])   # [6,7,8,9]

Element [0,1]     : 2
Last element      : 9
First 2 rows, last 2 cols:
 [[2 3]
 [5 6]]
Boolean mask > 5  : [6 7 8 9]


In [ ]:
# Universal Functions (ufuncs)
arr = np.array([1, 4, 9, 16])
print("Original   :", arr)
print("Square     :", np.square(arr))
print("Sqrt       :", np.sqrt(arr))
print("Log        :", np.log(arr))
print("Exp        :", np.exp(arr))

angles = np.array([0, np.pi/4, np.pi/2])
print("Sin(angles):", np.round(np.sin(angles), 4))

Original   : [ 1  4  9 16]
Square     : [  1  16  81 256]
Sqrt       : [1. 2. 3. 4.]
Log        : [0.         1.38629436 2.19722458 2.77258872]
Exp        : [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sin(angles): [0.     0.7071 1.    ]


In [ ]:
# Broadcasting
A = np.array([[1], [2], [3]])    # shape (3,1)
B = np.array([10, 20, 30])       # shape (3,)
print("A + B (broadcasting):\n", A + B)   # shape becomes (3,3)

A + B (broadcasting):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


# PART 4: NumPy Exercises

## Problem 1 - Array Creation

In [ ]:
import numpy as np

# 1. Empty array 2×2  (values are uninitialised — may look random)
empty_2x2 = np.empty((2, 2))
print("1. Empty 2×2:\n", empty_2x2)

# 2. All-ones array 4×2
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4×2:\n", ones_4x2)

# 3. Array filled with a constant value (fill_value = 7)
filled = np.full((3, 3), fill_value=7)
print("\n3. Full 3×3 with 7:\n", filled)

# 4. Zeros with same shape as an existing array
existing = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(existing)
print("\n4. zeros_like existing:\n", zeros_like)

# 5. Ones with same shape as existing
ones_like = np.ones_like(existing)
print("\n5. ones_like existing:\n", ones_like)

# 6. Convert Python list to NumPy array
new_list   = [1, 2, 3, 4]
np_array   = np.array(new_list)
print("\n6. List → NumPy array:", np_array, "| dtype:", np_array.dtype)

1. Empty 2×2:
 [[2.71828183e+00 5.45981500e+01]
 [8.10308393e+03 8.88611052e+06]]

2. Ones 4×2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3×3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. zeros_like existing:
 [[0 0 0]
 [0 0 0]]

5. ones_like existing:
 [[1 1 1]
 [1 1 1]]

6. List → NumPy array: [1 2 3 4] | dtype: int64


## Problem 2: Array Manipulation

In [ ]:
# 1. Values 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Values 10–49:\n", arr_10_49)

# 2. 3×3 matrix with values 0–8
matrix_0_8 = np.arange(9).reshape(3, 3)
print("\n2. 3×3 matrix (0–8):\n", matrix_0_8)

# 3. 3×3 identity matrix
identity = np.eye(3)
print("\n3. 3×3 Identity:\n", identity)

# 4. Random array of size 30 → find mean
rand_30  = np.random.random(30)
print("\n4. Mean of random 30-element array:", rand_30.mean())

# 5. 10×10 random array → min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10×10 random — min:", rand_10x10.min(), " max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element (index 4) with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse the array
arr = np.array([1, 2, 0, 0, 4, 0])
print("\n7. Reversed:", arr[::-1])

# 8. 2D array: 1 on border, 0 inside
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8. Border of 1s:\n", border)

# 9. 8×8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2]  = 1   # odd rows, even cols
checkerboard[::2,  1::2] = 1   # even rows, odd cols
print("\n9. Checkerboard 8×8:\n", checkerboard)

1. Values 10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3×3 matrix (0–8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3×3 Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random 30-element array: 0.6046871882817214

5. 10×10 random — min: 0.016024631689953606  max: 0.9971357316164235

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed: [0 4 0 0 2 1]

8. Border of 1s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard 8×8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem 3: Array Operations

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Addition
print("1. x + y:\n", x + y)

# 2. Subtraction
print("\n2. x - y:\n", x - y)

# 3. Scalar multiplication
print("\n3. x * 3:\n", x * 3)

# 4. Element-wise square
print("\n4. x ** 2:\n", x ** 2)

# 5. Dot products
print("\n5a. v · w (scalar)       :", np.dot(v, w))        # 9*11 + 10*12 = 219
print("5b. x · v (matrix-vector):", np.dot(x, v))
print("5c. x · y (matrix-matrix):\n", np.dot(x, y))

# 6. Concatenation
print("\n6a. x and y stacked vertically (rows):\n",  np.vstack((x, y)))
print("6b. v and w concatenated           :",  np.concatenate((v, w)))

# 7. Concatenating x (2D) with v (1D)
print("\n7. Attempting to concatenate x (2D) and v (1D):")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"ValueError: {e}")
    print("Explanation: np.concatenate requires all inputs to have the same number")
    print("of dimensions. x is 2D (shape 2×2) but v is 1D (shape (2,)).")
    print("Fix: reshape v to (1,2) or (2,1) first.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x ** 2:
 [[ 1  4]
 [ 9 25]]

5a. v · w (scalar)       : 219
5b. x · v (matrix-vector): [29 77]
5c. x · y (matrix-matrix):
 [[19 22]
 [50 58]]

6a. x and y stacked vertically (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w concatenated           : [ 9 10 11 12]

7. Attempting to concatenate x (2D) and v (1D):
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: np.concatenate requires all inputs to have the same number
of dimensions. x is 2D (shape 2×2) but v is 1D (shape (2,)).
Fix: reshape v to (1,2) or (2,1) first.


## Problem 4: Matrix Operations & Solving Linear Equations

In [ ]:
A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

A_inv = np.linalg.inv(A)
I     = np.eye(2)

# Proof 1: A · A⁻¹ = I
result1 = np.dot(A, A_inv)
print("Proof 1 — A · A⁻¹ (should be Identity):\n", np.round(result1, 10))

# Proof 2: AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nProof 2 — AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.allclose(AB, BA))   # False -> proven

# Proof 3: (AB)ᵀ = BᵀAᵀ
lhs = (np.dot(A, B)).T
rhs = np.dot(B.T, A.T)
print("\nProof 3 — (AB)ᵀ:\n", lhs)
print("BᵀAᵀ:\n", rhs)
print(np.allclose(lhs, rhs))   # True -> proven

Proof 1 — A · A⁻¹ (should be Identity):
 [[1. 0.]
 [0. 1.]]

Proof 2 — AB:
 [[23. 13.]
 [51. 29.]]
BA:
 [[36. 44.]
 [13. 16.]]
AB == BA? False

Proof 3 — (AB)ᵀ:
 [[23. 51.]
 [13. 29.]]
BᵀAᵀ:
 [[23. 51.]
 [13. 29.]]
True


In [ ]:
# Solving the System of Linear Equations
#
#   2x - 3y + z  = -1
#    x -  y + 2z = -3
#   3x +  y -  z =  9
#
#   Matrix form:  AX = B

coeff_A = np.array([[ 2, -3,  1],
                    [ 1, -1,  2],
                    [ 3,  1, -1]], dtype=float)

const_B = np.array([-1, -3, 9], dtype=float)

# Method 1 — Inverse: X = A⁻¹ B
A_inv    = np.linalg.inv(coeff_A)
X_method1 = np.dot(A_inv, const_B)
print("Solution via Inverse (X = A⁻¹B):", np.round(X_method1, 6))

# Method 2 — np.linalg.solve  (more numerically stable)
X_method2 = np.linalg.solve(coeff_A, const_B)
print("Solution via np.linalg.solve    :", np.round(X_method2, 6))

# Verify: A·X should equal B
print("\nVerification A·X =?", np.round(np.dot(coeff_A, X_method2), 6))
print("Expected B       :", const_B)

Solution via Inverse (X = A⁻¹B): [ 2.  1. -2.]
Solution via np.linalg.solve    : [ 2.  1. -2.]

Verification A·X =? [-1. -3.  9.]
Expected B       : [-1. -3.  9.]


##  Problem 5: How Fast is NumPy?

In [ ]:
import time
import numpy as np

SIZE = 1_000_000   # 1 million elements

# Pre-generate data
list_a = [float(i) for i in range(SIZE)]
list_b = [float(i) for i in range(SIZE)]
np_a   = np.array(list_a)
np_b   = np.array(list_b)


def time_it(label, func):
    """Run func(), measure elapsed time, and print a summary."""
    start  = time.time()
    result = func()
    elapsed = time.time() - start
    print(f"  {label:<35}: {elapsed:.5f} s")
    return elapsed


print("=" * 55)
print("1. Element-wise Addition (n =", SIZE, ")")
t_list = time_it("Python list",
                 lambda: [list_a[i] + list_b[i] for i in range(SIZE)])
t_np   = time_it("NumPy array",
                 lambda: np_a + np_b)
print(f"NumPy is ~{t_list/t_np:.1f}× faster")


print("\n" + "=" * 55)
print("2. Element-wise Multiplication (n =", SIZE, ")")
t_list = time_it("Python list",
                 lambda: [list_a[i] * list_b[i] for i in range(SIZE)])
t_np   = time_it("NumPy array",
                 lambda: np_a * np_b)
print(f"NumPy is ~{t_list/t_np:.1f}× faster")


print("\n" + "=" * 55)
print("3. Dot Product (n =", SIZE, ")")
t_list = time_it("Python list",
                 lambda: sum(list_a[i] * list_b[i] for i in range(SIZE)))
t_np   = time_it("NumPy array",
                 lambda: np.dot(np_a, np_b))
print(f"NumPy is ~{t_list/t_np:.1f}× faster")


print("\n" + "=" * 55)
print("4. Matrix Multiplication (1000 × 1000)")
SIZE_M  = 1000
mat_a_l = [[float(i+j) for j in range(SIZE_M)] for i in range(SIZE_M)]
mat_b_l = [[float(i*j+1) for j in range(SIZE_M)] for i in range(SIZE_M)]
np_mat_a = np.array(mat_a_l)
np_mat_b = np.array(mat_b_l)

def python_matmul(A, B):
    n = len(A)
    C = [[0.0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

print("Python matrix multiply is very slow — skipping full loop (would take minutes).")
print("     Timing a 50×50 sub-matrix to estimate...")
sub_a = mat_a_l[:50]; sub_b = mat_b_l[:50]
sub_a = [row[:50] for row in sub_a]; sub_b = [row[:50] for row in sub_b]
t_list = time_it("Python 50×50 matmul (estimated)",
                 lambda: python_matmul(sub_a, sub_b))
t_np   = time_it("NumPy 1000×1000 matmul          ",
                 lambda: np.dot(np_mat_a, np_mat_b))
print("NumPy does the full 1000×1000 in the time Python barely finishes 50×50!")
print("=" * 55)

1. Element-wise Addition (n = 1000000 )
  Python list                        : 0.06037 s
  NumPy array                        : 0.00206 s
NumPy is ~29.2× faster

2. Element-wise Multiplication (n = 1000000 )
  Python list                        : 0.05509 s
  NumPy array                        : 0.00215 s
NumPy is ~25.6× faster

3. Dot Product (n = 1000000 )
  Python list                        : 0.09536 s
  NumPy array                        : 0.00306 s
NumPy is ~31.2× faster

4. Matrix Multiplication (1000 × 1000)
Python matrix multiply is very slow — skipping full loop (would take minutes).
     Timing a 50×50 sub-matrix to estimate...
  Python 50×50 matmul (estimated)    : 0.00882 s
  NumPy 1000×1000 matmul             : 0.04480 s
NumPy does the full 1000×1000 in the time Python barely finishes 50×50!
